### ISSUE TITLE
jar 包下载不了

### ISSUE THREAD

**Issue by rachelliqian** [ck-jesse/l2cache#1]
jar 包下载不了
![image](https://user-images.githubusercontent.com/22114582/91627837-f3cbe100-e9ec-11ea-9894-38ddfd140dc9.png)

**Comment by ck-jesse** [comment]
目前还没有推送到公共的仓库里面，需要直接下载代码，然后编译打包才能

**Comment by ck-jesse** [comment]
1、已发布到maven的中央仓库，知悉。
2、具体地址：https://search.maven.org/search?q=g:io.github.ck-jesse
