### ISSUE TITLE
如何优雅扩展多租户特性

### ISSUE THREAD

**Issue by weaponready** [ck-jesse/l2cache#15]
假设提供了一个TenantContextHolder.getTenantId()工具，在什么位置使用比较合适呢

**Comment by ck-jesse** [comment]
关于多租户，我的建议是不用特别去做区分，如果一定要扩展的话，有两种方式：
一、简单的方式

- 直接在 cacheName 上做文章，把cacheName做成动态的拼接上租户Id

二、复杂的方式

- 从CacheBuilder开始扩展，将租户id传递到Cache对象（同cacheName一样），然后将租户id，cacheName，构建为缓存key

**Comment by ck-jesse** [comment]
重新梳理了一下，其实目前是支持动态去自定义key前缀的。

对于多租户模式下，如何动态自定义key前缀，具体如下：

方案：在CacheService.buildCacheKey(...)的实现方法中进行动态拼接即可
案例：NewGoodsPriceRevisionCacheService.buildCacheKey(...)

注意：
1、本地缓存：key的前缀是不包含cacheName的，可以减小key的长度，节省内存空间。由于是本地缓存，只需保证一个缓存维度下缓存key的唯一性即可，所以无需包含cacheName。

2、远程缓存：key的前缀是会包含cacheName的，由于是集中式缓存，所以需要通过cacheName+key来保证唯一性。
