### ISSUE TITLE
请问批量删除缓存是怎么操作的,对象的话给出其中几个字段是怎么命中的

### ISSUE THREAD

**Issue by jykSS** [ck-jesse/l2cache#16]
请问批量删除缓存是怎么操作的,假如我只更新了商品表的一个字段,但别的缓存的key是商品名和简介,没有商品id,这种能够删除吗,如果能的话,代码是怎么实现的

**Comment by ck-jesse** [comment]
1、目前没有提供批量删除的操作，后续可以考虑增加一个
2、别的缓存的key是商品名和简介，这种情况，需要在业务代码中，通过商品id找到商品名和简介去删除

**Comment by ck-jesse** [comment]
已增加批量删除缓存的功能。
