### ISSUE TITLE
目前支持最高的springboot版本是多少？

### ISSUE THREAD

**Issue by ljy-super** [ck-jesse/l2cache#21]
目前项目使用2.7.5版本的springboot
启动报错
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

**Comment by ck-jesse** [comment]
如果出现spring-boot版本冲突的情况，可以将l2cache中的spring-boot排除掉，使用项目中的版本即可。

可参考如下示例：

`
        <dependency>
            <groupId>io.github.ck-jesse</groupId>
            <artifactId>l2cache-spring-boot-starter</artifactId>
            <version>1.0.35</version>
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>
`

**Comment by ck-jesse** [comment]
l2cache目前只依赖spring-boot-starter-web模块，有使用到mvc能力，以及spring-context中的cache能力，若项目中出现版本冲突，建议排除l2cache中依赖，使用项目中的版本即可。

**Comment by ljy-super** [comment]
<dependency>
            <groupId>io.github.ck-jesse</groupId>
            <artifactId>l2cache-spring-boot-starter</artifactId>
            <version>1.0.35</version>
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-boot-starter-web</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-cloud-context</artifactId>
                    <groupId>org.springframework.cloud</groupId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by ck-jesse** [comment]
> 目前l2cache中支持的是 redission，暂未对不同的redis client进行适配。如果项目中使用到其他的redis client，又想用到l2cache的能力的话，目前只能同时配置两个redis的配置了，不过最终还是看你的取舍吧

**Comment by ljy-super** [comment]
> > 目前l2cache中支持的是 redission，暂未对不同的redis client进行适配。如果项目中使用到其他的redis client，又想用到l2cache的能力的话，目前只能同时配置两个redis的配置了，不过最终还是看你的取舍吧

已经处理

**Comment by ck-jesse** [comment]
> > > 目前l2cache中支持的是 redission，暂未对不同的redis client进行适配。如果项目中使用到其他的redis client，又想用到l2cache的能力的话，目前只能同时配置两个redis的配置了，不过最终还是看你的取舍吧
> 
> 已经处理

方便的话，了解一下，是用在什么业务下，使用感受如何

**Comment by ljy-super** [comment]
> > > > 目前l2cache中支持的是 redission，暂未对不同的redis client进行适配。如果项目中使用到其他的redis client，又想用到l2cache的能力的话，目前只能同时配置两个redis的配置了，不过最终还是看你的取舍吧
> > 
> > 
> > 已经处理
> 
> 方便的话，了解一下，是用在什么业务下，使用感受如何

商品列表，多实例本地缓存不一致问题。

**Comment by ck-jesse** [comment]
> > > > > 目前l2cache中支持的是 redission，暂未对不同的redis client进行适配。如果项目中使用到其他的redis client，又想用到l2cache的能力的话，目前只能同时配置两个redis的配置了，不过最终还是看你的取舍吧
> > > 
> > > 
> > > 已经处理
> > 
> > 
> > 方便的话，了解一下，是用在什么业务下，使用感受如何
> 
> 商品列表，多实例本地缓存不一致问题。

OK，若有问题，欢迎随时探讨和咨询

**Comment by zhoujin7** [comment]
[https://github.com/ck-jesse/l2cache/pull/41](https://github.com/ck-jesse/l2cache/pull/41)
将spring相关依赖的scope设置为provided，
可以避免这个问题

**Comment by ck-jesse** [comment]
springboot版本已更新到3.3.4
