### ISSUE TITLE
这么多Redis广播消息，是不是该注意一下client-output-buffer-limit pubsub 参数的配置

### ISSUE THREAD

**Issue by zxy1994** [ck-jesse/l2cache#22]
看到了有redis广播功能，建议提醒一下使用者关注 client-output-buffer-limit pubsub参数的配置。防止丢消息

**Comment by ck-jesse** [comment]
非常感谢，确实可以提醒使用者注意下这个参数的配置。

首先，从实际使用情况，以及压测的情况来看，暂时未发现关闭连接的情况。
其次，由于l2cache中发送的消息体大小是可控的（仅包含key值，不包含value），所以不会出现输出bigkey的情况。
因此，初步判断默认的输出缓存区是够用。

**Comment by ck-jesse** [comment]
已补充到注释里面（位置：RedisCacheSyncPolicy）
