### ISSUE TITLE
热点探测

### ISSUE THREAD

**Issue by huskyui** [ck-jesse/l2cache#23]
本来以为是框架自带的，原来是接入了jd的hotkey.哈哈哈

**Comment by ck-jesse** [comment]
做过一次技术调研，最终选择了接入jd-hotkey，具体可以看看这篇文章：

[l2cache [热key探测]技术方案调研](https://blog.csdn.net/icansoicrazy/article/details/130885982)

**Comment by huskyui** [comment]
> 做过一次技术调研，最终选择了接入jd-hotkey，具体可以看看这篇文章：
> 
> [l2cache [热key探测]技术方案调研](https://blog.csdn.net/icansoicrazy/article/details/130885982)

好的，我去看下这个文章

**Comment by huskyui** [comment]
其实我们公司之前分享过，还可以通过大数据的stream来达到探测热点数据。之前有同事分享过

**Comment by ck-jesse** [comment]
> 其实我们公司之前分享过，还可以通过大数据的stream来达到探测热点数据。之前有同事分享过

这是一个很好的实现思路。

如果引入这种方案的话，我可能会考虑以下几个点：
1、复杂度：引入大数据，必然会引入架构上的复杂性，那么，能否接受这种复杂性？方案的普适性如何？
2、适用性：实时的业务系统中，引入大数据实时计算，这是一种强耦合，是否合适？后续迭代和扩展怎么办？
3、成本高：大数据实时计算是很吃资源的，这个成本是否可以承受？
