### ISSUE TITLE
请问是否有支持缓存双删的计划

### ISSUE THREAD

**Issue by Gerrit1999** [ck-jesse/l2cache#29]
我正在使用您的仓库，目前发现它提供了二级缓存和缓存过期时间的支持，这对于许多应用场景来说是非常有用的。

在高并发和实时性要求较高的应用中，支持缓存双删可以提供更好的数据一致性，而不依赖于固定的过期时间。并且也可以与缓存过期时间结合使用，以满足不同的需求。

我想了解您是否考虑过在未来的版本中支持缓存双删策略，或者是否可以提供一些关于如何自行实现此策略的指导？任何关于此问题的建议或信息都将对我非常有帮助。

**Comment by ck-jesse** [comment]
这个想法很好，但目前在l2cache中并没有实现类似缓存双删的功能，不过有提供缓存删除的接口，可在业务逻辑中调用。

目前我想到的有如下几种实现方式：

1、缓存双删模式：先删缓存，再写DB，再删缓存【不建议使用】
可能网上有很多这方面的资料，业务侵入严重，硬编码，个人觉得实现起来较为麻烦，不建议使用。

2、先写再删模式：先写DB，再删缓存【建议使用】
实时性较好的一种方案，实现相对简单，缓存更新快速，但业务侵入严重，硬编码，极端情况下可能存在短时间的不一致（个人理解是可以接受的）。适用于大部分高并发场景。
高并发场景下，删除模式，会导致请求穿透到DB，对性能有一定影响。

3、双写模式：先写DB，再写缓存【建议使用】
实时性最好的一种方案，实现相对简单，缓存更新快速，但业务侵入严重，硬编码，且容易出现遗漏。适用于大部分高并发场景。
并发更新场景下，可能出现ABA的问题。实际业务中，并发修改同一个数据的情况多吗？是否可以在业务角度下进行控制呢？同一个时刻只允许一个修改操作？

4、binlog异步写入模式：先写DB，再监听binlog，投递到MQ，消费MQ并异步写入缓存【建议使用】
无业务侵入，无硬编码，通用方案，但实现相对复杂，构建binlog系统，且要接受一定的延迟（受主从同步速度的影响）。保证最终一致性，不保证实时性。

我这边实际上是，第三和第四这两种模式在混合使用。

另外，前三种模式，都存在业务入侵的问题，目前初步的想法是在l2cache中，通过自定义注解的方式，将对缓存的删除或更新操作抽象出来，从而达到与业务解耦的目的。
当然，这里可能会引入一些新的问题需要我们去解决。比如，一个业务场景中含多个业务维度的数据更新，此时，如何保证多个缓存维度和业务数据的数据一致性，等等。

希望以上内容，对你有一些帮助。

**Comment by Gerrit1999** [comment]
非常感谢您的详细解答，这对我理解这个问题和选择方案都很有帮助。

我发现了这个[项目](https://github.com/howaric/spring-enhanced-cache)，通过将Cache包装为一个持有监听器的Cache来实现延迟删除。具体地，当删除缓存时，监听器将缓存删除事件包装为一个延迟的操作，推到延迟队列；用一个守护线程去轮询该队列，取出延迟时间到达的删除操作，交给线程池异步执行。这样在业务代码中直接使用spring的`CacheEvict`注解就可以实现缓存双删。您觉得这个方案如何？

**Comment by ck-jesse** [comment]
1、看了下[spring-enhanced-cache](https://github.com/howaric/spring-enhanced-cache)的源码，确实挺好的，也很清晰，它实现的思路值得借鉴下。

2、不建议直接在spring-cache这层去实现自定义逻辑，因为对于l2cache而言，spring-cache只是一个上层应用，l2cache可以独立使用。

3、因此，建议直接在l2cache的 `com.github.jesse.l2cache.Cache` 这个层级上去实现我们自定义的逻辑，会更加的通用。

4、自定义的逻辑这里，可以借鉴下spring-enhanced-cache里面的实现方式，如它的监听器方式。当然，这里要特别注意，要实现的通用一些，因为如双删模式、先写后删模式、延迟双删模式等等都只是一种自定义逻辑而已。

**Comment by ck-jesse** [comment]
由于时间关系，暂时没有精力去实现这个功能，如果比较着急的话，建议你自己开发实现，开发完成后，欢迎提交一个PR。
