### ISSUE TITLE
可能出现一级缓存和二级缓存不一致

### ISSUE THREAD

**Issue by pop1213** [ck-jesse/l2cache#34]
看源码中加了一个openedL1Cache变量，注释说明是为了避免缓存不一致，按这个思路发现还是存在缓存不一致的可能性（理论上）。
如下代码中，当执行put时，先更新完二级缓存，此时关闭缓存导致一级缓存未更新。当将要清除一级缓存时此时打开一级缓存配置进而跳过了清除一级缓存的操作

```java
 public void put(Object key, Object value) {
        level2Cache.put(key, value);
        // a. 此时关闭一级缓存，一级缓存未更新
        if (ifL1Open(key)) {
            level1Cache.put(key, value);
        }
        // b. 此时打开一级缓存,
        this.ifEvictL1Cache(key);
    }    
```

**Comment by ck-jesse** [comment]
这是一个好问题，在极端的情况下，确实可能会出现这种问题。

当时这么设计的考虑如下：

1、其实这里我采用的是“双写模式“，它的优点是实时性好，缺点是可能存在ABA的问题，也就是你所提的一致性问题。

2、为什么选择“双写模式”呢？因为当时我们电商平台的流量比较大，二级缓存redis的压力比较高，告警频繁，经常要升配。若在这种高并发场景下，采用“先写再删模式”，会导致请求穿透到二级缓存redis甚至DB，对系统性能和稳定性有较大的影响。故而选择了双写模式来避免高并发场景下请求穿透到下游。

3、解决这个问题可以采用，先写再删模式，或者双删模式，两者都可以。

**Comment by ck-jesse** [comment]
我理解你问题的意思，这两种方案也可以的，不过简单点的做法是，先put二级缓存，再直接删除一级缓存，也就是我上面说的“先写再删”，实现上更简单一些。
