### ISSUE TITLE
maven中央仓库不是最新master的代码，版本不升级吗

### ISSUE THREAD

**Issue by yanyulun** [ck-jesse/l2cache#35]

**Comment by ck-jesse** [comment]
有更新的，从上一个推到中央仓库的版本，到现在更新的内容只是一些小的优化，不影响整体的功能使用，所以暂时未更新上去

**Comment by ck-jesse** [comment]
deploy了一个最新版本1.0.39到中央仓库

**Comment by yanyulun** [comment]
好的，感谢。还有个问题，现在我将一张表的所有记录以id作为key进行缓存，现在想要查询缓存中所有的记录，目前我想到的是将所有key存到一个Set集合变量里，这样增加或删除要修改set，还要考虑多实例之间同步的问题。你有什么好的解决方案吗？

**Comment by ck-jesse** [comment]
1、场景：以id作为key进行缓存，想查询所有缓存记录
2、必知：l2cache底层的数据结构采用的是String
3、分析：不建议采用set或map，因为当这个业务维度的数据较多时，会出现大key、数据倾斜、负载不均等问题
4、方案：在上层的业务应用中，进行分页逻辑的处理，可以从分页处理逻辑中找到对应的id列表，再通过l2cache中CacheService 这一个缓存层中提供的批量查询缓存的方法来获取缓存数据

**Comment by ck-jesse** [comment]
1、场景：以id作为key进行缓存，想查询所有缓存记录
2、必知：l2cache底层的数据结构采用的是String
3、分析：不建议采用set或map，因为当这个业务维度的数据较多时，会出现大key、数据倾斜、负载不均等问题
4、方案：在上层的业务应用中，进行分页逻辑的处理，可以从分页处理逻辑中找到对应的id列表，再通过l2cache中CacheService 这一个缓存层中提供的批量查询缓存的方法来获取缓存数据

**Comment by yanyulun** [comment]
你的意思是先从数据库查询id列表吗？那感觉有点怪，本来缓存就是想减少数据库访问的

**Comment by ck-jesse** [comment]
1、逻辑是这样的：在按照分页方式查询数据时，将id列表按照分页的方式缓存（这里可以提前预热），然后再根据id列表批量获取具体的缓存数据。
2、这种方式也要结合业务场景来实现，比如电商平台的一个场景：首页-会场-商品列表，会场下面是有多个商品的，这种情况下可以将会场和商品id列表关联起来，存放在redis中。至于是不是要按照分页方式存储，这个要看你的述求了。
