### ISSUE TITLE
通知消息里的cacheType是小写，但是初始化的时候是大写，消息处理不了

### ISSUE THREAD

**Issue by huayanYu** [ck-jesse/l2cache#38]
最新版本，JDK21,springboot2.7.18

初始化的时候
![image](https://github.com/ck-jesse/l2cache/assets/16700837/c0d08c73-96d3-43ec-8efc-992e64e720ba)

收到消息的时候
![image](https://github.com/ck-jesse/l2cache/assets/16700837/00569698-941b-4fe5-acff-aad92b834dea)

大小写不一致，就找不到了

**Comment by huayanYu** [comment]
问题大概根源在这里 构建的时候
![image](https://github.com/ck-jesse/l2cache/assets/16700837/d2ab7771-6057-4377-a346-b2f945d054e2)

发送消息前的时候
![image](https://github.com/ck-jesse/l2cache/assets/16700837/7527d5e6-2097-4b84-9fdf-26d86019d37c)

不知道为啥没有其他人反馈。。

**Comment by ck-jesse** [comment]
> 问题大概根源在这里 构建的时候 ![image](https://private-user-images.githubusercontent.com/16700837/333046013-d2ab7771-6057-4377-a346-b2f945d054e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDMyODIsIm5iZiI6MTcyMzAwMjk4MiwicGF0aCI6Ii8xNjcwMDgzNy8zMzMwNDYwMTMtZDJhYjc3NzEtNjA1Ny00Mzc3LWEzNDYtYjJmOTQ1ZDA1NGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAzNTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YTQwNzk5ZmQ3ZTgzODljNDFmZGFhMmUwMzM3ZDMyODBlNDU5N2QxODBlMjNiZGRmNjQ5ZjNmMTQ2NGE5YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ydGpl1kvuElS_7POLRI--PGqU4yjbHhXwLczUxYVSBo)
> 
> 发送消息前的时候 ![image](https://private-user-images.githubusercontent.com/16700837/333047070-7527d5e6-2097-4b84-9fdf-26d86019d37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDMyODIsIm5iZiI6MTcyMzAwMjk4MiwicGF0aCI6Ii8xNjcwMDgzNy8zMzMwNDcwNzAtNzUyN2Q1ZTYtMjA5Ny00Yjg0LTlmZGYtMjZkODYwMTlkMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAzNTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZGMxOTkxZjU5ZGIwZWM0YTRhYjEzOWJmOWYyOTBkZDZiN2YzZmU3YjM3YjM5MWM5NjFhYjc5YzkyZTkxZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.en5MgNiAtQ1g3SSZSLeQnes36q_x2IhGemQN-Kb2rQg)
> 
> 不知道为啥没有其他人反馈。。

可能没有人这么使用过，都是按照exapmle中的示例来使用的。

不过确实是个问题，后面我抽空优化下这里

**Comment by ck-jesse** [comment]
> 问题大概根源在这里 构建的时候 ![image](https://private-user-images.githubusercontent.com/16700837/333046013-d2ab7771-6057-4377-a346-b2f945d054e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTMzMDksIm5iZiI6MTcyNzM1MzAwOSwicGF0aCI6Ii8xNjcwMDgzNy8zMzMwNDYwMTMtZDJhYjc3NzEtNjA1Ny00Mzc3LWEzNDYtYjJmOTQ1ZDA1NGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEyMTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYjQyZWVkYTJhOGIyMWI5YTBkMzA1NmY2NDA4MzYyMDRhOThjYmUwYzZhZDM4NTY2Y2M4NmQ1NDMyZDZmZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dEikd9YpqIiNuz8pAkVu5Vh-Zeqwe0pIPiV8LlxBPA4)
> 
> 发送消息前的时候 ![image](https://private-user-images.githubusercontent.com/16700837/333047070-7527d5e6-2097-4b84-9fdf-26d86019d37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTMzMDksIm5iZiI6MTcyNzM1MzAwOSwicGF0aCI6Ii8xNjcwMDgzNy8zMzMwNDcwNzAtNzUyN2Q1ZTYtMjA5Ny00Yjg0LTlmZGYtMjZkODYwMTlkMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEyMTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YjRjOTk5YTdjZWRhODQ0NjkxZDc5ZWZmNDY2NGMxZDM3YzUyZjI5NmRhMTNlMTE0NjY4MjMwM2UwZTg5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qlVw1cpRAtK7RwRnBuBNB1S8QJA9OiV1V4QKq8CZmWg)
> 
> 不知道为啥没有其他人反馈。。

已修正

**Comment by ck-jesse** [comment]
@huayanYu 已修正
