### ISSUE TITLE
L2cache能否支持单个服务连接多个独立的redis实例

### ISSUE THREAD

**Issue by ahdsjkhdjkashdjkaEWUQEY1231** [ck-jesse/l2cache#46]
如标题所描述，我们有个服务连接了多个不同的redis实例，想了解L2cache是否能支持这种场景

**Comment by ahdsjkhdjkashdjkaEWUQEY1231** [comment]
我的描述可能有些问题，上面说的“不同的”代表着它们是独立的实例，并不是集群中的节点

**Comment by ahdsjkhdjkashdjkaEWUQEY1231** [comment]
你理解的没错，就是多个redis数据源的场景。我原以为可以通过配置文件设置多个数据源，这样就可以通过spring cache的注解实现，这样的话会更简单，开箱即用。但是不支持的话，我打算通过创建不同的cache对象来实现我的功能。

**Comment by ck-jesse** [comment]
目前确实不支持，方便了解下你的业务场景吗？为何会出现一个服务里面，有多个redis数据源的情况？不同的缓存维度，是固定使用某个redis，还是一个缓存维度需要动态切换redis?

**Comment by ck-jesse** [comment]
已新增功能：支持多redis实例的场景，支持为cacheName配置指定的redissonClient实例

案例见：l2cache-example 中的 com.github.jesse.l2cache.example.cache.OrderCacheService
