### ISSUE TITLE
请问一下nullValueCache目前的作用是什么？感觉只有在查询出空置的时候会put一下，但从未查询

### ISSUE THREAD

**Issue by mrbcy** [ck-jesse/l2cache#7]
本来以为这个是用来避免缓存穿透的，但好像没有起到相应的作用？

**Comment by ck-jesse** [comment]
为什么没有起到相应的作用呢？NullValue 的作用就是用来防止缓存穿透的呀。使用时，要根据业务场景来设置NullValue的过期时间。
