### ISSUE TITLE
weeget-infinite-hotkey-client

### ISSUE THREAD

**Issue by stones-d** [ck-jesse/l2cache#9]
私服貌似已经down了，该包下载不了

**Comment by ck-jesse** [comment]
不好意思这个包还未开源出来，后续会抽离出来。可以先将pom文件中的这个jar包给注释掉。

**Comment by ck-jesse** [comment]
1、已发布到maven的中央仓库，知悉。
2、具体地址：https://search.maven.org/search?q=g:io.github.ck-jesse
